### ISSUE TITLE
“叫地主，不叫，打牌，过牌”按钮是灰色的，无法操作

### ISSUE THREAD

**Issue by longhtml** [jxy918/hyperf-ddz#1]
# 登录后

登录成功
进入房间成功:{"card":[50,20,36,4,37,53,38,6,54,22,55,23,40,57,59,61,29],"chair_id":3,"calltype":1,"is_master":0,"is_first_round":false,"is_game_over":false}
进入房间成功:{"card":[50,20,36,4,37,53,38,6,54,22,55,23,40,57,59,61,29],"chair_id":3,"calltype":1,"is_master":0,"is_first_round":false,"is_game_over":false}
心跳数据:

# 开始AI

[root@localhost ai]# php ai.php  long
2020/08/14 19:13:22 [INFO]  原数据:.i¤code£msg¢OK¤data¦status§success§is_room 
2020/08/14 19:13:22 [INFO]  ----------------------------------------------------------------------------------------------
2020/08/14 19:13:22 [INFO]  cmd = 1 scmd =105 len=50 method=loginSucessResp
2020/08/14 19:13:22 [INFO]  登录成功, 开始游戏请求
2020/08/14 19:13:22 [INFO]  原数据:lk¤code£msg¢OK¤data¤cardڑ#348*
                                                                 ¨chair_id¨calltype©is_master®is_first_round¬is_game_over
2020/08/14 19:13:22 [INFO]  ----------------------------------------------------------------------------------------------
2020/08/14 19:13:22 [INFO]  cmd = 1 scmd =107 len=112 method=enterRoomSuccResp
2020/08/14 19:13:22 [INFO]  进入房间成功数据:{"card":[17,18,2,35,51,3,19,52,21,7,56,25,42,27,11,28,78],"chair_id":1,"calltype":0,"is_master":0,"is_first_round":false,"is_game_over":false}
2020/08/14 19:14:22 [INFO]  原数据:$f¤code£msg¢OK¤data¤timeʀ
2020/08/14 19:14:22 [INFO]  心跳(毫秒):2

“叫地主，不叫，打牌，过牌”  按钮是灰色的，无法操作。  求解

**Comment by jxy918** [comment]
不是当前用户操作就是灰的，三个用户，轮到谁操作，按钮就亮的。



---原始邮件---
发件人: "longhtml"<notifications@github.com&gt;
发送时间: 2020年8月14日(周五) 晚上7:46
收件人: "jxy918/hyperf-ddz"<hyperf-ddz@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [jxy918/hyperf-ddz] “叫地主，不叫，打牌，过牌”按钮是灰色的，无法操作 (#1)




 
登录后
 
登录成功
 进入房间成功:{"card":[50,20,36,4,37,53,38,6,54,22,55,23,40,57,59,61,29],"chair_id":3,"calltype":1,"is_master":0,"is_first_round":false,"is_game_over":false}
 进入房间成功:{"card":[50,20,36,4,37,53,38,6,54,22,55,23,40,57,59,61,29],"chair_id":3,"calltype":1,"is_master":0,"is_first_round":false,"is_game_over":false}
 心跳数据:
 
开始AI
 
[root@localhost ai]# php ai.php  long
 2020/08/14 19:13:22 [INFO]  原数据:.i¤code£msg¢OK¤data¦status§success§is_room
 2020/08/14 19:13:22 [INFO]  ----------------------------------------------------------------------------------------------
 2020/08/14 19:13:22 [INFO]  cmd = 1 scmd =105 len=50 method=loginSucessResp
 2020/08/14 19:13:22 [INFO]  登录成功, 开始游戏请求
 2020/08/14 19:13:22 [INFO]  原数据:lk¤code£msg¢OK¤data¤cardڑ#348*
 ¨chair_id¨calltype©is_master®is_first_round¬is_game_over
 2020/08/14 19:13:22 [INFO]  ----------------------------------------------------------------------------------------------
 2020/08/14 19:13:22 [INFO]  cmd = 1 scmd =107 len=112 method=enterRoomSuccResp
 2020/08/14 19:13:22 [INFO]  进入房间成功数据:{"card":[17,18,2,35,51,3,19,52,21,7,56,25,42,27,11,28,78],"chair_id":1,"calltype":0,"is_master":0,"is_first_round":false,"is_game_over":false}
 2020/08/14 19:14:22 [INFO]  原数据:$f¤code£msg¢OK¤data¤timeʀ
 2020/08/14 19:14:22 [INFO]  心跳(毫秒):2
 
“叫地主，不叫，打牌，过牌”按钮是灰色的，无法操作。  求解
